name: managment-center-build

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    # paths:
    #   - "deploy/todo-demo-api/*"
    #   - "packages/todo-demo-api/**"
    #   - ".github/workflows/build-backend-prod.yml"

jobs:
  managment-center-build-docker:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      # Checkout latest or specific tag
      - name: checkout
        uses: actions/checkout@v3
      - name: checkout tag
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.inputs.version }}

      # Assign environment variables used in subsequent steps
      - name: Env variable assignment
        run: echo "image_repository_name=$(echo $GITHUB_WORKFLOW | sed 's/-build$//')" >>${GITHUB_ENV}
      # TAG_NAME defaults to 'latest' if not a release or manual deployment
      - name: Assign version
        run: |
          docker build . -t passon/baccarat-managment-server --progress=plain -f ./pkg/baccarat-managment-center/Dockerfile
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push passon/baccarat-managment-server
          docker logout
